_wandb:
    value:
        cli_version: 0.22.2
        e:
            ihbvavz3st5kx03417e1y8itwj55p5yv:
                args:
                    - --fname
                    - /home/s185927/thesis/vjepa2/configs/train/vitg16/x_axis_finetune/x_axis_finetune_025pct.yaml
                    - --devices
                    - cuda:0
                codePath: experiments/sim_training_different_fractions/train_single_model_early_stopping.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1992352894976"
                        used: "169703149568"
                email: lassesofus@gmail.com
                executable: /home/s185927/.conda/envs/vjepa2-312/bin/python
                git:
                    commit: ca6f220a6997cff71cdec368b3a4d6ba43c69f9c
                    remote: git@github.com:lassesofus/thesis.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-1ad6fff7-327f-50bb-3a45-0c8473d16b74
                host: comp-ws6211
                memory:
                    total: "131965460480"
                os: Linux-6.12.0-55.31.1.el10_0.x86_64-x86_64-with-glibc2.39
                program: /home/s185927/thesis/experiments/sim_training_different_fractions/train_single_model_early_stopping.py
                python: CPython 3.12.12
                root: /home/s185927/thesis/vjepa2
                startedAt: "2026-01-17T16:41:51.057389Z"
                writerId: ihbvavz3st5kx03417e1y8itwj55p5yv
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
app:
    value: vjepa_droid
cpus_per_task:
    value: 12
data:
    value:
        batch_size: 8
        camera_views:
            - left_mp4_path
        crop_size: 256
        dataset_fpcs:
            - 8
        datasets:
            - /data/s185927/droid_sim/axis_aligned/x_axis/splits/train_025pct.csv
        fps: 4
        num_workers: 12
        patch_size: 16
        pin_mem: true
        stereo_view: false
        tubelet_size: 2
data_aug:
    value:
        auto_augment: false
        horizontal_flip: false
        motion_shift: false
        random_resize_aspect_ratio:
            - 1
            - 1
        random_resize_scale:
            - 1
            - 1
        reprob: 0
folder:
    value: /data/s185927/vjepa2/weights/droid/x_axis_finetune_025pct
loss:
    value:
        auto_steps: 2
        loss_exp: 1
        normalize_reps: true
        reg_coeff: 0
mem_per_gpu:
    value: 220G
meta:
    value:
        context_encoder_key: target_encoder
        dtype: bfloat16
        early_stopping_min_delta: 0.0001
        early_stopping_patience: 10
        eval_freq: 100
        load_encoder: true
        load_predictor: true
        pretrain_checkpoint: /home/s185927/.cache/torch/hub/checkpoints/vjepa2-ac-vitg.pt
        resume_checkpoint: null
        save_every_freq: 25
        seed: 239
        target_encoder_key: target_encoder
        use_sdpa: true
        val_freq: 1
model:
    value:
        model_name: vit_giant_xformers
        pred_depth: 24
        pred_embed_dim: 1024
        pred_is_frame_causal: true
        pred_num_heads: 16
        uniform_power: true
        use_activation_checkpointing: true
        use_extrinsics: false
        use_rope: true
nodes:
    value: 4
optimization:
    value:
        anneal: 15
        enc_lr_scale: 0
        epochs: 100
        final_lr: 0
        final_weight_decay: 0.04
        ipe: 300
        lr: 0.0001
        start_lr: 2e-05
        warmup: 5
        weight_decay: 0.04
tasks_per_node:
    value: 8
val_data:
    value:
        batch_size: 8
        camera_views:
            - left_mp4_path
        crop_size: 256
        dataset_fpcs:
            - 8
        datasets:
            - /data/s185927/droid_sim/axis_aligned/x_axis/splits/val_trajectories.csv
        fps: 4
        num_workers: 12
        patch_size: 16
        pin_mem: true
        stereo_view: false
        tubelet_size: 2
