app: vjepa_droid
cpus_per_task: 12
data:
  batch_size: 8
  camera_views:
  - left_mp4_path
  crop_size: 256
  dataset_fpcs:
  - 8
  datasets:
  - /data/s185927/droid_sim/axis_aligned/x/splits/train_075pct.csv
  fps: 4
  num_workers: 12
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 2
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 1.777
  - 1.777
  reprob: 0.0
folder: /data/s185927/vjepa2/weights/droid/x_axis_finetune_075pct
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
mem_per_gpu: 220G
meta:
  context_encoder_key: target_encoder
  dtype: bfloat16
  eval_freq: 100
  load_predictor: true
  pretrain_checkpoint: /home/s185927/.cache/torch/hub/checkpoints/vjepa2-ac-vitg.pt
  resume_checkpoint: null
  save_every_freq: 25
  seed: 239
  target_encoder_key: target_encoder
  use_sdpa: true
  load_encoder: true
  early_stopping_patience: 50
  val_freq: 5
  early_stopping_min_delta: 0.001
model:
  model_name: vit_giant_xformers
  pred_depth: 24
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_rope: true
nodes: 4
optimization:
  anneal: 15
  epochs: 100
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: 300
  lr: 0.0001
  start_lr: 2.0e-05
  warmup: 5
  weight_decay: 0.04
  enc_lr_scale: 0.0
tasks_per_node: 8
val_data:
  batch_size: 8
  camera_views:
  - left_mp4_path
  crop_size: 256
  dataset_fpcs:
  - 8
  datasets:
  - /data/s185927/droid_sim/axis_aligned/x/splits/val_trajectories.csv
  fps: 4
  num_workers: 12
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 2
